# This file is automatically generated — do not edit by hand.

PolyNumOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PolyNumOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars         = NULL,
            orientation  = "vertical",
            showViolin   = FALSE,
            showBox      = TRUE,
            showJitter   = FALSE,
            showMean     = FALSE,
            showRug      = FALSE,
            showOutliers = TRUE,
            violinScale  = "area",
            plotAlpha    = 80L,
            boxWidth     = 55L,
            jitterWidth  = 20L,
            pointSize    = 1.5,
            colorScheme  = "viridis",
            themeChoice  = "minimal",
            showGridX    = TRUE,
            showGridY    = FALSE,
            title        = "",
            xlab         = "",
            ylab         = "",
            plotWidth    = 650L,
            plotHeight   = 480L,
            ...) {

            super$initialize(
                package      = "PolyUniPlots",
                name         = "PolyNum",
                requiresData = TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars", vars,
                suggested = list("continuous"),
                permitted = list("numeric"))

            private$..orientation <- jmvcore::OptionList$new(
                "orientation", orientation,
                options = list("vertical", "horizontal"),
                default = "vertical")

            private$..showViolin   <- jmvcore::OptionBool$new("showViolin",   showViolin,   default = FALSE)
            private$..showBox      <- jmvcore::OptionBool$new("showBox",      showBox,      default = TRUE)
            private$..showJitter   <- jmvcore::OptionBool$new("showJitter",   showJitter,   default = FALSE)
            private$..showMean     <- jmvcore::OptionBool$new("showMean",     showMean,     default = FALSE)
            private$..showRug      <- jmvcore::OptionBool$new("showRug",      showRug,      default = FALSE)
            private$..showOutliers <- jmvcore::OptionBool$new("showOutliers", showOutliers, default = TRUE)

            private$..violinScale <- jmvcore::OptionList$new(
                "violinScale", violinScale,
                options = list("area", "count", "width"),
                default = "area")

            private$..plotAlpha   <- jmvcore::OptionInteger$new("plotAlpha",   plotAlpha,   min = 0L,   max = 100L,  default = 80L)
            private$..boxWidth    <- jmvcore::OptionInteger$new("boxWidth",    boxWidth,    min = 5L,   max = 100L,  default = 55L)
            private$..jitterWidth <- jmvcore::OptionInteger$new("jitterWidth", jitterWidth, min = 0L,   max = 50L,   default = 20L)
            private$..pointSize   <- jmvcore::OptionNumber$new( "pointSize",   pointSize,   min = 0.2,  max = 5.0,   default = 1.5)

            private$..colorScheme <- jmvcore::OptionList$new(
                "colorScheme", colorScheme,
                options = list("viridis","plasma","mako","rocket","turbo","tableau","dark","pastel","warm","cold"),
                default = "viridis")

            private$..themeChoice <- jmvcore::OptionList$new(
                "themeChoice", themeChoice,
                options = list("minimal","classic","bw","light"),
                default = "minimal")

            private$..showGridX  <- jmvcore::OptionBool$new("showGridX", showGridX, default = TRUE)
            private$..showGridY  <- jmvcore::OptionBool$new("showGridY", showGridY, default = FALSE)
            private$..title      <- jmvcore::OptionString$new("title",  title,  default = "")
            private$..xlab       <- jmvcore::OptionString$new("xlab",   xlab,   default = "")
            private$..ylab       <- jmvcore::OptionString$new("ylab",   ylab,   default = "")
            private$..plotWidth  <- jmvcore::OptionInteger$new("plotWidth",  plotWidth,  min = 300L, max = 2000L, default = 650L)
            private$..plotHeight <- jmvcore::OptionInteger$new("plotHeight", plotHeight, min = 200L, max = 2000L, default = 480L)

            self$.addOption(private$..vars)
            self$.addOption(private$..orientation)
            self$.addOption(private$..showViolin)
            self$.addOption(private$..showBox)
            self$.addOption(private$..showJitter)
            self$.addOption(private$..showMean)
            self$.addOption(private$..showRug)
            self$.addOption(private$..showOutliers)
            self$.addOption(private$..violinScale)
            self$.addOption(private$..plotAlpha)
            self$.addOption(private$..boxWidth)
            self$.addOption(private$..jitterWidth)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..colorScheme)
            self$.addOption(private$..themeChoice)
            self$.addOption(private$..showGridX)
            self$.addOption(private$..showGridY)
            self$.addOption(private$..title)
            self$.addOption(private$..xlab)
            self$.addOption(private$..ylab)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        vars         = function() private$..vars$value,
        orientation  = function() private$..orientation$value,
        showViolin   = function() private$..showViolin$value,
        showBox      = function() private$..showBox$value,
        showJitter   = function() private$..showJitter$value,
        showMean     = function() private$..showMean$value,
        showRug      = function() private$..showRug$value,
        showOutliers = function() private$..showOutliers$value,
        violinScale  = function() private$..violinScale$value,
        plotAlpha    = function() private$..plotAlpha$value,
        boxWidth     = function() private$..boxWidth$value,
        jitterWidth  = function() private$..jitterWidth$value,
        pointSize    = function() private$..pointSize$value,
        colorScheme  = function() private$..colorScheme$value,
        themeChoice  = function() private$..themeChoice$value,
        showGridX    = function() private$..showGridX$value,
        showGridY    = function() private$..showGridY$value,
        title        = function() private$..title$value,
        xlab         = function() private$..xlab$value,
        ylab         = function() private$..ylab$value,
        plotWidth    = function() private$..plotWidth$value,
        plotHeight   = function() private$..plotHeight$value),
    private = list(
        ..vars         = NA,
        ..orientation  = NA,
        ..showViolin   = NA,
        ..showBox      = NA,
        ..showJitter   = NA,
        ..showMean     = NA,
        ..showRug      = NA,
        ..showOutliers = NA,
        ..violinScale  = NA,
        ..plotAlpha    = NA,
        ..boxWidth     = NA,
        ..jitterWidth  = NA,
        ..pointSize    = NA,
        ..colorScheme  = NA,
        ..themeChoice  = NA,
        ..showGridX    = NA,
        ..showGridY    = NA,
        ..title        = NA,
        ..xlab         = NA,
        ..ylab         = NA,
        ..plotWidth    = NA,
        ..plotHeight   = NA))

PolyNumResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PolyNumResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name    = "",
                title   = "Multiple Numeric Plots")
            self$add(jmvcore::Image$new(
                options      = options,
                name         = "plot",
                title        = "Distribution Comparison",
                width        = 650,
                height       = 480,
                renderFun    = ".plot",
                requiresData = TRUE,
                refs         = list("ggplot2")))
        })
)

PolyNumBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PolyNumBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package    = "PolyUniPlots",
                name       = "PolyNum",
                version    = c(1, 0, 0),
                options    = options,
                results    = PolyNumResults$new(options=options),
                data       = data,
                datasetId  = datasetId,
                analysisId = analysisId,
                revision   = revision)
        })
)

#' Multiple Numeric Plots
#'
#' @param data     A data frame.
#' @param vars     Numeric variables to plot.
#' @param ...      Additional options (see \code{PolyNumOptions}).
#' @return A results object.
#' @export
PolyNum <- function(data, vars, ...) {
    if (!requireNamespace("jmvcore", quietly=TRUE))
        stop("PolyNum requires jmvcore")
    options  <- PolyNumOptions$new(vars=vars, ...)
    analysis <- PolyNumClass$new(options=options, data=data)
    analysis$run()
    analysis$results
}
